version: '3.8'

services:
  # Nokia SR Linux PE1
  pe1-srlinux:
    image: ghcr.io/nokia/srlinux:23.10.1
    container_name: clab-aurora-pe1-srlinux
    hostname: pe1-srlinux
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.10
    ports:
      - "830:830"    # NETCONF
      - "443:443"    # RESTCONF  
      - "9339:9339"  # gNMI
    volumes:
      - ./configs/pe1-srlinux.cfg:/etc/opt/srlinux/config.json:ro
    privileged: true
    environment:
      - SRLINUX_INIT_CONFIG=/etc/opt/srlinux/config.json
    
  # Nokia SR Linux PE2
  pe2-srlinux:
    image: ghcr.io/nokia/srlinux:23.10.1
    container_name: clab-aurora-pe2-srlinux
    hostname: pe2-srlinux
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.11
    ports:
      - "831:830"    # NETCONF
      - "444:443"    # RESTCONF
      - "9340:9339"  # gNMI
    volumes:
      - ./configs/pe2-srlinux.cfg:/etc/opt/srlinux/config.json:ro
    privileged: true
    environment:
      - SRLINUX_INIT_CONFIG=/etc/opt/srlinux/config.json

  # Nokia SR Linux P1 (Core)
  p1-srlinux:
    image: ghcr.io/nokia/srlinux:23.10.1
    container_name: clab-aurora-p1-srlinux
    hostname: p1-srlinux
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.20
    ports:
      - "835:830"    # NETCONF
      - "448:443"    # RESTCONF
      - "9344:9339"  # gNMI
    volumes:
      - ./configs/p1-srlinux.cfg:/etc/opt/srlinux/config.json:ro
    privileged: true
    environment:
      - SRLINUX_INIT_CONFIG=/etc/opt/srlinux/config.json

  # Customer Edge 1
  ce1-linux:
    image: alpine:latest
    container_name: clab-aurora-ce1-linux
    hostname: ce1-linux
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.30
      customer-west:
        ipv4_address: 192.168.100.1
    command: >
      sh -c "
      apk add --no-cache iproute2 iputils tcpdump &&
      ip route add 192.168.200.0/24 via 192.168.100.254 &&
      tail -f /dev/null
      "

  # Customer Edge 2  
  ce2-linux:
    image: alpine:latest
    container_name: clab-aurora-ce2-linux
    hostname: ce2-linux
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.31
      customer-east:
        ipv4_address: 192.168.200.1
    command: >
      sh -c "
      apk add --no-cache iproute2 iputils tcpdump &&
      ip route add 192.168.100.0/24 via 192.168.200.254 &&
      tail -f /dev/null
      "

  # AURORA-IBN Controller
  aurora-controller:
    image: python:3.11-slim
    container_name: clab-aurora-controller
    hostname: aurora-controller
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.100
    ports:
      - "8000:8000"   # API Server
      - "8080:8080"   # Web UI
      - "8888:8888"   # Jupyter
    volumes:
      - ../src:/app/aurora-ibn:ro
      - ../examples:/app/examples:ro
      - ./test-results:/app/results
    working_dir: /app
    environment:
      - PYTHONPATH=/app/aurora-ibn
      - AURORA_LLM_PROVIDER=mlx
      - AURORA_LLM_MODEL=mlx-community/Llama-3.2-3B-Instruct-4bit
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y git curl build-essential &&
      pip install --no-cache-dir aiohttp pyyaml asyncssh netaddr pandas jupyter &&
      echo 'AURORA-IBN Controller Ready' &&
      tail -f /dev/null
      "

  # Test automation container
  aurora-tester:
    image: python:3.11-slim
    container_name: clab-aurora-tester
    hostname: aurora-tester
    networks:
      aurora-mgmt:
        ipv4_address: 172.25.25.101
    volumes:
      - ../:/app/aurora-ibn
      - ./test-results:/app/results
    working_dir: /app/aurora-ibn/containerlab
    environment:
      - PYTHONPATH=/app/aurora-ibn/src
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y git curl iputils-ping &&
      pip install --no-cache-dir aiohttp pyyaml asyncssh netaddr &&
      echo 'AURORA-IBN Tester Ready' &&
      tail -f /dev/null
      "

networks:
  aurora-mgmt:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.25.0/24
          gateway: 172.25.25.1

  customer-west:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.254

  customer-east:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.254

volumes:
  aurora-data: